
/* eslint no-multi-spaces:0 */

/*--------------------------------------------------
  GLOBAL ACTIONS
---------------------------------------------------*/
// Reset Password Message Types
export const SUCCESS                                = 'SUCCESS';
export const ERROR                                  = 'ERROR';

// General
export const CO_BROWSING_ENABLED                    = 'CO_BROWSING_ENABLED';
export const APP_DATA_HAS_BEEN_UPDATED              = 'APP_DATA_HAS_BEEN_UPDATED';
export const APP_REFERENCE_DATA_HAS_BEEN_RECEIVED   = 'APP_REFERENCE_DATA_HAS_BEEN_RECEIVED';
export const OTHER_PLEASE_TYPE                      = 'OTHER_PLEASE_TYPE';
export const RECEIVE_APP_API_URL                    = 'RECEIVE_APP_API_URL';

// User
export const GET_USER_SUCCESS                         = 'GET_USER_DATA_SUCCESS';
export const SET_PASSWORD_VERIFICATION_STATUS         = 'SET_PASSWORD_VERIFICATION_STATUS';
export const TOGGLE_PASSWORD_VERIFICATION_IN_PROGRESS = 'TOGGLE_PASSWORD_VERIFICATION_IN_PROGRESS';

// Yodlee
export const YODLEE_GET_FASTLINK_DATA_SUCCESS       = 'YODLEE_FASTLINK_DATA_SUCCESS';
export const YODLEE_GET_FASTLINK_DATA_FAIL          = 'YODLEE_FASTLINK_DATA_FAIL';
export const YODLEE_GET_ACCT_TRANSACTIONS_SUCCESS   = 'YODLEE_GET_ACCT_TRANSACTIONS_SUCCESS';
export const YODLEE_GET_ACCT_TRANSACTIONS_FAIL      = 'YODLEE_GET_ACCT_TRANSACTIONS_FAIL';
export const YODLEE_GET_USER_TRANSACTIONS_SUCCESS   = 'YODLEE_GET_USER_TRANSACTIONS_SUCCESS';
export const YODLEE_GET_USER_TRANSACTIONS_FAIL      = 'YODLEE_GET_USER_TRANSACTIONS_FAIL';
export const YODLEE_GET_ACCOUNTS_SUCCESS            = 'YODLEE_GET_ACCOUNTS_SUCCESS';
export const YODLEE_GET_ACCOUNTS_FAIL               = 'YODLEE_GET_ACCOUNTS_FAIL';
export const YODLEE_GET_ENABLED_ACCOUNTS_SUCCESS    = 'YODLEE_GET_ENABLED_ACCOUNTS_SUCCESS';
export const YODLEE_GET_ENABLED_ACCOUNTS_FAIL       = 'YODLEE_GET_ENABLED_ACCOUNTS_FAIL';
export const YODLEE_GET_ACCOUNT_SUCCESS             = 'YODLEE_GET_ACCOUNT_SUCCESS';
export const YODLEE_GET_ACCOUNT_FAIL                = 'YODLEE_GET_ACCOUNT_FAIL';
export const YODLEE_GET_ACCOUNT_BALANCES_SUCCESS    = 'YODLEE_GET_ACCOUNT_BALANCES_SUCCESS';
export const YODLEE_GET_ACCOUNT_BALANCES_FAIL       = 'YODLEE_GET_ACCOUNT_BALANCES_FAIL';

// Connect
export const CONNECT_ACCOUNTS_SUCCESS               = 'CONNECT_ACCOUNTS_SUCCESS';
export const CONNECT_ACCOUNTS_FAIL                  = 'CONNECT_ACCOUNTS_FAIL';
export const DISCONNECT_ACCOUNTS_SUCCESS            = 'DISCONNECT_ACCOUNT_SUCCESS';
export const DISCONNECT_ACCOUNTS_FAIL               = 'DISCONNECT_ACCOUNTS_FAIL';

// Local DB Transactions
export const SAVE_TRANSACTION                       = 'SAVE_TRANSACTION';
export const SAVE_TRANSACTION_SUCCESS               = 'SAVE_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_FAIL                  = 'SAVE_TRANSACTION_FAIL';
export const UPDATE_TRANSACTION_SUCCESS             = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAIL                = 'UPDATE_TRANSACTION_FAIL';
export const GET_ALL_TRANSACTIONS                   = 'GET_ALL_TRANSACTIONS';
export const GET_ALL_TRANSACTIONS_SUCCESS           = 'GET_ALL_TRANSACTIONS_SUCCESS';
export const GET_ALL_TRANSACTIONS_FAIL              = 'GET_ALL_TRANSACTIONS_FAIL';
export const GET_TRANSACTIONS_BY_ACCOUNT            = 'GET_TRANSACTIONS_BY_ACCOUNT';
export const GET_TRANSACTIONS_BY_ACCOUNT_SUCCESS    = 'GET_TRANSACTIONS_BY_ACCOUNT_SUCCESS';
export const GET_TRANSACTIONS_BY_ACCOUNT_FAIL       = 'GET_TRANSACTIONS_BY_ACCOUNT_FAIL';
export const GET_TRANSACTIONS_BY_USER_REQUEST       = 'GET_TRANSACTIONS_BY_USER_REQUEST';
export const GET_TRANSACTIONS_BY_USER_SUCCESS       = 'GET_TRANSACTIONS_BY_USER_SUCCESS';
export const GET_TRANSACTIONS_BY_USER_FAIL          = 'GET_TRANSACTIONS_BY_USER_FAIL';
export const IMPORT_TRANSACTIONS_SUCCESS            = 'IMPORT_TRANSACTIONS_SUCCESS';
export const IMPORT_TRANSACTIONS_FAIL               = 'IMPORT_TRANSACTIONS_FAIL';
export const TOGGLE_ACCOUNT_OPTIONS_MENU_SUCCESS    = 'TOGGLE_ACCOUNT_OPTIONS_MENU_SUCCESS';

// Transaction Fieldsets
export const UPSERT_TRANSACTION_FIELDSET            = 'UPSERT_TRANSACTION_FIELDSET';
export const UPSERT_TRANSACTION_FIELDSET_SUCCESS    = 'UPSERT_TRANSACTION_FIELDSET_SUCCESS';
export const UPSERT_TRANSACTION_FIELDSET_FAIL       = 'UPSERT_TRANSACTION_FIELDSET_FAIL';
export const GET_BILL_FIELDSETS_SUCCESS             = 'GET_BILL_FIELDSETS_SUCCESS';
export const GET_BILL_FIELDSETS_FAIL                = 'GET_BILL_FIELDSETS_FAIL';
export const GET_INCOME_FIELDSETS_SUCCESS           = 'GET_INCOME_FIELDSETS_SUCCESS';
export const GET_INCOME_FIELDSETS_FAIL              = 'GET_INCOME_FIELDSETS_FAIL';
export const IMPORT_BILLS                           = 'IMPORT_BILLS';
export const IMPORT_BILLS_SUCCESS                   = 'IMPORT_BILLS_SUCCESS';
export const IMPORT_BILLS_FAIL                      = 'IMPORT_BILLS_FAIL';
export const IMPORT_INCOMES                         = 'IMPORT_INCOMES';
export const IMPORT_INCOMES_SUCCESS                 = 'IMPORT_INCOMES_SUCCESS';
export const IMPORT_INCOMES_FAIL                    = 'IMPORT_INCOMES_FAIL';
export const PREDICT_BILLS_SUCCESS                  = 'PREDICT_BILLS_SUCCESS';
export const PREDICT_BILLS_FAIL                     = 'PREDICT_BILLS_FAIL';

// Appointments
export const SAVE_APPOINTMENT                       = 'SAVE_APPOINTMENT';
export const SAVE_APPOINTMENT_SUCCESS               = 'SAVE_APPOINTMENT_SUCCESS';
export const SAVE_APPOINTMENT_FAIL                  = 'SAVE_APPOINTMENT_FAIL';
export const GET_APPOINTMENTS                       = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_SUCCESS               = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL                  = 'GET_APPOINTMENTS_FAIL';

// Accounts
export const GET_ACCOUNTS_FROM_LOCAL_STORAGE_SUCCESS            = 'GET_ACCOUNTS_FROM_LOCAL_STORAGE_SUCCESS';
export const GET_ACCOUNTS_FROM_LOCAL_STORAGE_FAIL               = 'GET_ACCOUNTS_FROM_LOCAL_STORAGE_FAIL';
export const GET_ACCOUNTS_SETTINGS_FROM_LOCAL_STORAGE_SUCCESS   = 'GET_ACCOUNTS_SETTINGS_FROM_LOCAL_STORAGE_SUCCESS';
export const GET_ACCOUNTS_SETTINGS_FROM_LOCAL_STORAGE_FAIL      = 'GET_ACCOUNTS_SETTINGS_FROM_LOCAL_STORAGE_FAIL';
export const UPDATE_ACCOUNTS_SUCCESS                            = 'UPDATE_ACCOUNTS_SUCCESS';
export const UPDATE_ACCOUNTS_FAIL                               = 'UPDATE_ACCOUNTS_FAIL';
export const IMPORT_ACCOUNTS_SUCCESS                            = 'IMPORT_ACCOUNTS_SUCCESS';
export const IMPORT_ACCOUNTS_FAIL                               = 'IMPORT_ACCOUNTS_FAIL';
export const DELETE_PROVIDER_ACCOUNT_SUCCESS                    = 'DELETE_PROVIDER_ACCOUNT_SUCCESS';

// Analysis
export const GET_PEREX_ANALYSIS                     = 'GET_PEREX_ANALYSIS';
export const GET_PEREX_ANALYSIS_SUCCESS             = 'GET_PEREX_ANALYSIS_SUCCESS';
export const GET_PEREX_ANALYSIS_FAIL                = 'GET_PEREX_ANALYSIS_FAIL';

// Goals
export const CREATE_GOAL_SUCCESS                    = 'CREATE_GOALS_SUCCESS';
export const CREATE_GOAL_FAIL                       = 'CREATE_GOALS_FAIL';
export const GET_GOAL_SUCCESS                       = 'GET_GOAL_SUCCESS';
export const GET_GOAL_FAIL                          = 'GET_GOAL_FAIL';
export const GET_GOALS_SUCCESS                      = 'GET_GOALS_SUCCESS';
export const GET_GOALS_FAIL                         = 'GET_GOALS_FAIL';
export const TOGGLE_GOAL_SUBMISSION                 = 'TOGGLE_GOAL_SUBMISSION';

// Refresh
export const REFRESH_TRANSACTIONS                   = 'REFRESH_TRANSACTIONS';
export const REFRESH_TRANSACTIONS_SUCCESS           = 'REFRESH_TRANSACTIONS_SUCCESS';
export const REFRESH_TRANSACTIONS_FAIL              = 'REFRESH_TRANSACTIONS_FAIL';

// Finance Section
export const CREATE_FINANCE_SUMMARY_SUCCESS         = 'CREATE_FINANCE_SUMMARY_SUCCESS';
export const CREATE_FINANCE_SUMMARY_FAIL            = 'CREATE_FINANCE_SUMMARY_FAIL';
export const CREATE_COMPARISON_SUMMARY_SUCCESS      = 'CREATE_COMPARISON_SUMMARY_SUCCESS';
export const CREATE_COMPARISON_SUMMARY_FAIL         = 'CREATE_COMPARISON_SUMMARY_FAIL';

// Fin Plan
export const GET_FIN_PLAN_SUCCESS                   = 'GET_FIN_PLAN_SUCCESS';
export const GET_FIN_PLAN_FAIL                      = 'GET_FIN_PLAN_FAIL';
export const GET_FIN_PLANS_SUCCESS                  = 'GET_FIN_PLANS_SUCCESS';
export const GET_FIN_PLANS_FAIL                     = 'GET_FIN_PLANS_FAIL';
export const CREATE_FIN_PLAN_SUCCESS                = 'CREATE_FIN_PLAN_SUCCESS';
export const CREATE_FIN_PLAN_FAIL                   = 'CREATE_FIN_PLAN_FAIL';
export const CHANGE_FORM_FIELD_TYPE                 = 'CHANGE_FORM_FIELD_TYPE';
export const UPDATE_FIN_PLAN                        = 'UPDATE_FIN_PLAN';

// Fin Plan - Payment
export const CREATE_FIN_PLAN_PAYMENT_SUCCESS        = 'CREATE_FIN_PLAN_PAYMENT_SUCCESS';
export const CREATE_FIN_PLAN_PAYMENT_FAIL           = 'CREATE_FIN_PLAN_PAYMENT_FAIL';
export const SUBMIT_PAYMENT_FORM                    = 'SUBMIT_PAYMENT_FORM';
export const SUBMIT_PAYMENT_FORM_FAIL               = 'SUBMIT_PAYMENT_FORM_FAIL';
export const UPDATE_FIN_PLAN_PAYMENT_SUCCESS        = 'UPDATE_FIN_PLAN_PAYMENT_SUCCESS';

// Fin Plan - Breadcrumbs
export const GET_FIN_PLAN_BREADCRUMBS               = 'GET_FIN_PLAN_BREADCRUMBS';
export const GET_FIN_PLAN_BREADCRUMBS_SUCCESS       = 'GET_FIN_PLAN_BREADCRUMBS_SUCCESS';
export const GET_FIN_PLAN_BREADCRUMBS_FAIL          = 'GET_FIN_PLAN_BREADCRUMBS_FAIL';
export const UPDATE_FIN_PLAN_BREADCRUMB             = 'UPDATE_FIN_PLAN_BREADCRUMB';
export const UPDATE_FIN_PLAN_BREADCRUMB_SUCCESS     = 'UPDATE_FIN_PLAN_BREADCRUMB_SUCCESS';
export const UPDATE_FIN_PLAN_BREADCRUMB_FAIL        = 'UPDATE_FIN_PLAN_BREADCRUMB_FAIL';
export const GET_FIN_PLAN_BREADCRUMB_SUCCESS        = 'GET_FIN_PLAN_BREADCRUMB_SUCCESS';
export const GET_FIN_PLAN_BREADCRUMB_FAIL           = 'GET_FIN_PLAN_BREADCRUMB_FAIL';

// Fin Plan - Personal Details
export const TOGGLE_CO_CLIENT                         = 'TOGGLE_CO_CLIENT';
export const SET_CO_CLIENT_VISIBILITY                 = 'SET_CO_CLIENT_VISIBILITY';
export const CHANGE_NUMBER_OF_CHILDREN                = 'CHANGE_NUMBER_OF_CHILDREN';
export const RECEIVE_FIN_PLAN_PERSONAL_DETAILS        = 'RECEIVE_FIN_PLAN_PERSONAL_DETAILS';
export const CREATE_FIN_PLAN_PERSONAL_DETAILS_SUCCESS = 'CREATE_FIN_PLAN_PERSONAL_DETAILS_SUCCESS';

// Fin Plan - Goals
export const GET_FIN_PLAN_GOALS_SUCCESS             = 'GET_FIN_PLAN_GOALS_SUCCESS';
export const GET_FIN_PLAN_GOALS_FAIL                = 'GET_FIN_PLAN_GOALS_FAIL';
export const CREATE_FIN_PLAN_GOAL_SUCCESS           = 'CREATE_FIN_PLAN_GOAL_SUCCESS';
export const CREATE_FIN_PLAN_GOAL_FAIL              = 'CREATE_FIN_PLAN_GOAL_FAIL';
export const UPDATE_FIN_PLAN_GOAL_SUCCESS           = 'UPDATE_FIN_PLAN_GOAL_SUCCESS';
export const UPDATE_FIN_PLAN_GOAL_FAIL              = 'UPDATE_FIN_PLAN_GOAL_FAIL';
export const DELETE_FIN_PLAN_GOAL_SUCCESS           = 'DELETE_FIN_PLAN_GOAL_SUCCESS';
export const DELETE_FIN_PLAN_GOAL_FAIL              = 'DELETE_FIN_PLAN_GOAL_FAIL';

// Fin Plan - Income
export const RECEIVE_FIN_PLAN_INCOME                = 'RECEIVE_FIN_PLAN_INCOME';
export const UPDATE_FIN_PLAN_CURRENT_INCOME_SOURCE  = 'UPDATE_FIN_PLAN_CURRENT_INCOME_SOURCE';
export const TOGGLE_FIN_PLAN_INCOME_FORM            = 'TOGGLE_FIN_PLAN_INCOME_FORM';
export const CREATE_FIN_PLAN_INCOME_SUCCESS         = 'CREATE_FIN_PLAN_INCOME_SUCCESS';
export const CREATE_FIN_PLAN_INCOME_FAIL            = 'CREATE_FIN_PLAN_INCOME_FAIL';
export const UPDATE_FIN_PLAN_INCOME_SUCCESS         = 'UPDATE_FIN_PLAN_INCOME_SUCCESS';
export const UPDATE_FIN_PLAN_INCOME_FAIL            = 'UPDATE_FIN_PLAN_INCOME_FAIL';
export const DELETE_FIN_PLAN_INCOME_SUCCESS         = 'DELETE_FIN_PLAN_INCOME_SUCCESS';
export const DELETE_FIN_PLAN_INCOME_FAIL            = 'DELETE_FIN_PLAN_INCOME_FAIL';
export const SUBMIT_FIN_PLAN_INCOME_FORM            = 'SUBMIT_FIN_PLAN_INCOME_FORM';
export const SUBMIT_FIN_PLAN_INCOME_FORM_FAIL       = 'SUBMIT_FIN_PLAN_INCOME_FORM_FAIL';
export const TOGGLE_FORM_STATE                      = 'TOGGLE_FORM_STATE';
export const CLEAR_FORM_TOGGLE_STATES               = 'CLEAR_FORM_TOGGLE_STATES';
export const ADD_TAX_TABLE_ITEM                     = 'ADD_TAX_TABLE_ITEM';
export const REMOVE_TAX_TABLE_ITEM                  = 'REMOVE_TAX_TABLE_ITEM';
export const CANCEL_INCOME_FORM                     = 'CANCEL_INCOME_FORM';

// Fin Plan - Assets
export const UPDATE_ASSET_FORM_TYPE                 = 'UPDATE_ASSET_FORM_TYPE';
export const TOGGLE_BANK_ACCOUNT                    = 'TOGGLE_BANK_ACCOUNT';
export const CREATE_FIN_PLAN_ASSET_SUCCESS          = 'CREATE_FIN_PLAN_ASSET_SUCCESS';
export const CREATE_FIN_PLAN_ASSET_FAIL             = 'CREATE_FIN_PLAN_ASSET_SUCCESS';
export const UPDATE_FIN_PLAN_ASSET_SUCCESS          = 'UPDATE_FIN_PLAN_ASSET_SUCCESS';
export const UPDATE_FIN_PLAN_ASSET_FAIL             = 'UPDATE_FIN_PLAN_ASSET_FAIL';
export const DELETE_FIN_PLAN_ASSET_SUCCESS          = 'DELETE_FIN_PLAN_ASSET_SUCCESS';
export const DELETE_FIN_PLAN_ASSET_FAIL             = 'DELETE_FIN_PLAN_ASSET_FAIL';
export const SUBMIT_FIN_PLAN_ASSET_FORM             = 'SUBMIT_FIN_PLAN_ASSET_FORM';
export const SUBMIT_FIN_PLAN_ASSET_FORM_FAIL        = 'SUBMIT_FIN_PLAN_ASSET_FORM_FAIL';
export const UPDATE_FIN_PLAN_CURRENT_ASSET          = 'UPDATE_FIN_PLAN_CURRENT_ASSET';
export const UPLOAD_SUCCESS_RETIREMENT_ACCOUNT      = 'UPLOAD_SUCCESS_RETIREMENT_ACCOUNT';
export const TOGGLE_FIN_PLAN_ASSET_CREATION_IN_PROGRESS = 'TOGGLE_FIN_PLAN_ASSET_CREATION_IN_PROGRESS';

// Additional Assets
export const TOOGLE_ADD_ADDITIONAL_ASSET_MODAL      = 'TOOGLE_ADD_ADDITIONAL_ASSET_MODAL';
export const UPDATE_ADDITIONAL_ASSET_MODAL_TYPE     = 'UPDATE_ADDITIONAL_ASSET_MODAL_TYPE';
export const SET_SELECTED_ADDITIONAL_ASSET          = 'SET_SELECTED_ADDITIONAL_ASSET';
export const RESET_REQUEST_SUCCESS                  = 'RESET_REQUEST_SUCCESS';
export const CREATE_ADDITIONAL_ASSET                = 'CREATE_ADDITIONAL_ASSET';
export const CREATE_ADDITIONAL_ASSET_SUCCESS        = 'CREATE_ADDITIONAL_ASSET_SUCCESS';
export const CREATE_ADDITIONAL_ASSET_FAIL           = 'CREATE_ADDITIONAL_ASSET_FAIL';
export const UPDATE_ADDITIONAL_ASSET                = 'UPDATE_ADDITIONAL_ASSET';
export const UPDATE_ADDITIONAL_ASSET_SUCCESS        = 'UPDATE_ADDITIONAL_ASSET_SUCCESS';
export const UPDATE_ADDITIONAL_ASSET_FAIL           = 'UPDATE_ADDITIONAL_ASSET_FAIL';
export const DELETE_ADDITIONAL_ASSET                = 'DELETE_ADDITIONAL_ASSET';
export const DELETE_ADDITIONAL_ASSET_SUCCESS        = 'DELETE_ADDITIONAL_ASSET_SUCCESS';
export const DELETE_ADDITIONAL_ASSET_FAIL           = 'DELETE_ADDITIONAL_ASSET_FAIL';
export const GET_ADDITIONAL_ASSETS                  = 'GET_ADDITIONAL_ASSETS';
export const GET_ADDITIONAL_ASSETS_SUCCESS          = 'GET_ADDITIONAL_ASSETS_SUCCESS';
export const GET_ADDITIONAL_ASSETS_FAIL             = 'GET_ADDITIONAL_ASSETS_FAIL';
export const SUBMIT_ADDITIONAL_ASSET_FORM           = 'SUBMIT_ADDITIONAL_ASSET_FORM';
export const SUBMIT_ADDITIONAL_ASSET_FORM_FAIL      = 'SUBMIT_ADDITIONAL_ASSET_FORM_FAIL';

// Fin Plan - Insurance
export const SHOW_INSURANCE_FORM                    = 'SHOW_INSURANCE_FORM';
export const CREATE_FIN_PLAN_INSURANCE_FAIL         = 'CREATE_FIN_PLAN_INSURANCE_FAIL';
export const CREATE_FIN_PLAN_INSURANCE_SUCCESS      = 'CREATE_FIN_PLAN_INSURANCE_SUCCESS';
export const UPDATE_FIN_PLAN_INSURANCE_SUCCESS      = 'UPDATE_FIN_PLAN_INSURANCE_SUCCESS';
export const UPDATE_FIN_PLAN_INSURANCE_FAIL         = 'UPDATE_FIN_PLAN_INSURANCE_FAIL';
export const DELETE_FIN_PLAN_INSURANCE_SUCCESS      = 'DELETE_FIN_PLAN_INSURANCE_SUCCESS';
export const DELETE_FIN_PLAN_INSURANCE_FAIL         = 'DELETE_FIN_PLAN_INSURANCE_FAIL';
export const SUBMIT_INSURANCE_FORM                  = 'SUBMIT_FIN_PLAN_INSURANCE_FORM';
export const SUBMIT_INSURANCE_FORM_FAIL             = 'SUBMIT_FIN_PLAN_INSURANCE_FORM_FAIL';
export const UPDATE_CURRENT_INSURANCE_POLICY        = 'UPDATE_CURRENT_INSURANCE_POLICY';
export const TOGGLE_FIN_PLAN_INSURANCE_UPDATE       = 'TOGGLE_FIN_PLAN_INSURANCE_UPDATE';

// Fin Plan - Liabilities
export const ADD_LIABILITY                          = 'ADD_LIABILITY';
export const UPDATE_LIABILITY                       = 'UPDATE_LIABILITY';
export const DELETE_LIABILITY                       = 'DELETE_LIABILITY';
export const TOGGLE_LIABILITY                       = 'TOGGLE_LIABILITY';
export const TOGGLE_LIABILITY_ACCOUNTS              = 'TOGGLE_LIABILITY_ACCOUNTS';
export const SUBMIT_FIN_PLAN_LIABILITY_REQUEST      = 'SUBMIT_FIN_PLAN_LIABILITY_REQUEST';
export const SUBMIT_FIN_PLAN_LIABILITY_REQUEST_FAIL = 'SUBMIT_FIN_PLAN_LIABILITY_REQUEST_FAIL';
export const CREATE_FIN_PLAN_LIABILITY_SUCCESS      = 'CREATE_FIN_PLAN_LIABILITY_SUCCESS';
export const CREATE_FIN_PLAN_LIABILITY_FAIL         = 'CREATE_FIN_PLAN_LIABILITY_FAIL';
export const UPDATE_FIN_PLAN_LIABILITY_FAIL         = 'UPDATE_FIN_PLAN_LIABILITY_FAIL';
export const UPDATE_FIN_PLAN_LIABILITY_SUCCESS      = 'UPDATE_FIN_PLAN_LIABILITY_SUCCESS';
export const DELETE_FIN_PLAN_LIABILITY_SUCCESS      = 'DELETE_FIN_PLAN_LIABILITY_SUCCESS';
export const DELETE_FIN_PLAN_LIABILITY_FAIL         = 'DELETE_FIN_PLAN_LIABILITY_FAIL';

// Fin Plan - Transactions
export const SYNC_ALL_FIN_PLAN_TRANSACTIONS         = 'SYNC_ALL_FIN_PLAN_TRANSACTIONS';
export const SYNC_ALL_FIN_PLAN_TRANSACTIONS_FAIL    = 'SYNC_ALL_FIN_PLAN_TRANSACTIONS_FAIL';
export const CREATE_FIN_PLAN_TRANSACTIONS_SUCCESS   = 'CREATE_FIN_PLAN_TRANSACTIONS_SUCCESS';
export const CREATE_FIN_PLAN_TRANSACTIONS_FAIL      = 'CREATE_FIN_PLAN_TRANSACTIONS_FAIL';
export const RECEIVE_FIN_PLAN_TRANSACTIONS          = 'RECEIVE_FIN_PLAN_TRANSACTIONS';

// Fin Plan - Other Expenses
export const CREATE_FIN_PLAN_OTHER_EXPENSE_SUCCESS     = 'CREATE_FIN_PLAN_OTHER_EXPENSE_SUCCESS';
export const CREATE_FIN_PLAN_OTHER_EXPENSE_FAIL        = 'CREATE_FIN_PLAN_OTHER_EXPENSE_FAIL';
export const UPDATE_FIN_PLAN_OTHER_EXPENSE_SUCCESS     = 'UPDATE_FIN_PLAN_OTHER_EXPENSE_SUCCESS';
export const UPDATE_FIN_PLAN_OTHER_EXPENSE_FAIL        = 'UPDATE_FIN_PLAN_OTHER_EXPENSE_FAIL';
export const DELETE_FIN_PLAN_OTHER_EXPENSE_SUCCESS     = 'DELETE_FIN_PLAN_OTHER_EXPENSE_SUCCESS';
export const DELETE_FIN_PLAN_OTHER_EXPENSE_FAIL        = 'DELETE_FIN_PLAN_OTHER_EXPENSE_FAIL';
export const GET_FIN_PLAN_OTHER_EXPENSES_SUCCESS       = 'GET_FIN_PLAN_OTHER_EXPENSES_SUCCESS';
export const GET_FIN_PLAN_OTHER_EXPENSES_FAIL          = 'GET_FIN_PLAN_OTHER_EXPENSES_FAIL';
export const BULK_CREATE_FIN_PLAN_OTHER_EXPENSES_SUCCESS = 'BULK_CREATE_FIN_PLAN_OTHER_EXPENSES_SUCCESS';
export const BULK_CREATE_FIN_PLAN_OTHER_EXPENSES_FAIL  = 'BULK_CREATE_FIN_PLAN_OTHER_EXPENSES_FAIL';
export const SUBMIT_FIN_PLAN_BILLS_FORM                = 'SUBMIT_FIN_PLAN_BILLS_FORM';
export const SUBMIT_FIN_PLAN_BILLS_FORM_FAIL           = 'SUBMIT_FIN_PLAN_BILLS_FORM';
export const UPDATE_FIN_PLAN_BILLS_COMMENT             = 'UPDATE_FIN_PLAN_BILLS_COMMENT';
export const UPDATE_FIN_PLAN_BILLS_COMMENT_FOR_STORE   = 'UPDATE_FIN_PLAN_BILLS_COMMENT_FOR_STORE';
export const UPDATE_FIN_PLAN_BILLS_COMMENT_SUCCESS     = 'UPDATE_FIN_PLAN_BILLS_COMMENT_SUCCESS';
export const UPDATE_FIN_PLAN_BILLS_COMMENT_FAIL        = 'UPDATE_FIN_PLAN_BILLS_COMMENT_FAIL';
export const GET_FIN_PLAN_BILLS_COMMENT_SUCCESS        = 'GET_FIN_PLAN_BILLS_COMMENT_SUCCESS';
export const GET_FIN_PLAN_BILLS_COMMENT_FAIL           = 'GET_FIN_PLAN_BILLS_COMMENT_FAIL';

// Fin Plan - Financial Questions
export const ADD_MAJOR_INCOME_EVENT                 = 'ADD_MAJOR_INCOME_EVENT';
export const ADD_MAJOR_EXPENSE_EVENT                = 'ADD_MAJOR_EXPENSE_EVENT';
export const DELETE_MAJOR_EVENT                     = 'DELETE_MAJOR_EVENT';
export const UPDATE_MAJOR_EVENT                     = 'UPDATE_MAJOR_EVENT';
export const COMPLETE_FIN_PLAN_QUESTION             = 'COMPLETE_FIN_PLAN_QUESTION';
export const SUBMIT_FIN_PLAN_QUESTIONS_REQUEST      = 'SUBMIT_FIN_PLAN_QUESTIONS_REQUEST';
export const SUBMIT_FIN_PLAN_QUESTIONS_REQUEST_FAIL = 'SUBMIT_FIN_PLAN_QUESTIONS_REQUEST_FAIL';
export const CREATE_FIN_PLAN_QUESTIONS_SUCCESS      = 'CREATE_FIN_PLAN_QUESTIONS_SUCCESS';
export const UPDATE_FIN_PLAN_QUESTIONS_SUCCESS      = 'UPDATE_FIN_PLAN_QUESTIONS_SUCCESS';
export const SUBMIT_FIN_PLAN_QUESTIONS_SUCCESS      = 'SUBMIT_FIN_PLAN_QUESTIONS_SUCCESS';
export const SET_FIN_PLAN_QUESTIONS_ENABLE_REINITILIZATION = 'SET_FIN_PLAN_QUESTIONS_ENABLE_REINITILIZATION';

export const SHOW_CARD_ERROR                        = 'SHOW_CARD_ERROR';

/*--------------------------------------------------
  LOCATION-SPECIFIC ACTIONS
---------------------------------------------------*/
// Advisor Login
export const CHANGE_ADVISOR_LOGIN_FORM              = 'CHANGE_ADVISOR_LOGIN_FORM';
export const CLEAR_ADVISOR_LOGIN_MESSAGE            = 'CLEAR_ADVISOR_LOGIN_MESSAGE';
export const DISPLAY_ADVISOR_LOGIN_ERROR            = 'DISPLAY_ADVISOR_LOGIN_ERROR';
export const SENDING_ADVISOR_LOGIN_REQUEST          = 'SENDING_ADVISOR_LOGIN_REQUEST';

// Advisor Dashboard
export const RECEIVE_ADVISOR_DASHBOARD_DATA           = 'RECEIVE_ADVISOR_DASHBOARD_DATA';
export const CHANGE_ADVISOR_DASHBOARD_SEARCH          = 'CHANGE_ADVISOR_DASHBOARD_SEARCH';
export const ADVISOR_DASHBOARD_TOGGLE_CALENDAR          = 'ADVISOR_DASHBOARD_TOGGLE_CALENDAR';
export const TOGGLE_SENDING_ADVISOR_DASHBOARD_REQUEST = 'TOGGLE_SENDING_ADVISOR_DASHBOARD_REQUEST';

// Login
export const LOGIN                                  = 'LOGIN';
export const CHANGE_LOGIN_FORM                      = 'CHANGE_LOGIN_FORM';
export const CLEAR_LOGIN_MESSAGE                    = 'CLEAR_LOGIN_MESSAGE';
export const DISPLAY_LOGIN_ERROR                    = 'DISPLAY_LOGIN_ERROR';
export const SENDING_LOGIN_REQUEST                  = 'SENDING_LOGIN_REQUEST';
export const PASSWORD_RESET_MESSAGE                 = 'PASSWORD_RESET_MESSAGE';
export const TOGGLE_FORGOT_PASSWORD                 = 'TOGGLE_FORGOT_PASSWORD';
export const LOGIN_RECAPTCHA_LOADED                 = 'LOGIN_RECAPTCHA_LOADED';
export const LOGIN_RECAPTCHA_ACCEPTED               = 'LOGIN_RECAPTCHA_ACCEPTED';

// Signup
export const TOGGLE_TOC                             = 'TOGGLE_TOC';
export const SIGNUP_MESSAGE                         = 'SIGNUP_MESSAGE';
export const CHANGE_SIGNUP_FORM                     = 'CHANGE_SIGNUP_FORM';
export const SENDING_SIGNUP_REQUEST                 = 'SENDING_SIGNUP_REQUEST';
export const SIGNUP_RECAPTCHA_LOADED                = 'SIGNUP_RECAPTCHA_LOADED';
export const SIGNUP_RECAPTCHA_ACCEPTED              = 'SIGNUP_RECAPTCHA_ACCEPTED';

// Reset Password
export const RESET_PASSWORD_ERROR                   = 'RESET_PASSWORD_ERROR';
export const CHANGE_RESET_PASSWORD_FORM             = 'CHANGE_RESET_PASSWORD_FORM';
export const SENDING_RESET_PASSWORD_REQUEST         = 'SENDING_RESET_PASSWORD_REQUEST';
export const TOGGLE_PASSWORD_RESET_SUCCESS_MESSAGE  = 'TOGGLE_PASSWORD_RESET_SUCCESS_MESSAGE';

// Page Wrapper
export const READY_TO_LOAD_PAGE                     = 'READY_TO_LOAD_PAGE';

// Advisor Connect
export const SUBMIT_APPOINTMENT_FORM                    = 'SUBMIT_APPOINTMENT_FORM';
export const SUBMIT_APPOINTMENT_FORM_SUCCESS            = 'SUBMIT_APPOINTMENT_FORM_SUCCESS';
export const SUBMIT_APPOINTMENT_FORM_FAIL               = 'SUBMIT_APPOINTMENT_FORM_FAIL';
export const SUBMIT_ADVISOR_CONNECT_INFO_FORM           = 'SUBMIT_ADVISOR_CONNECT_INFO_FORM';
export const CHANGE_ADVISOR_CONNECT_FORM_FIELD_TYPE     = 'CHANGE_ADVISOR_CONNECT_FORM_FIELD_TYPE';
export const SUBMIT_ADVISOR_CONNECT_INFO_FORM_SUCCESS   = 'SUBMIT_ADVISOR_CONNECT_INFO_FORM_SUCCESS';
export const SUBMIT_ADVISOR_CONNECT_INFO_FORM_FAIL      = 'SUBMIT_APPOINTMENT_FORM_FAIL';

// FinPlan Goals
export const UPDATE_FIN_PLAN_SELECTED_OPTION         = 'UPDATE_FIN_PLAN_SELECTED_OPTION';
export const SUBMIT_FIN_PLAN_GOAL_FORM               = 'SUBMIT_FIN_PLAN_GOAL_FORM';
export const SUBMIT_FIN_PLAN_GOAL_FORM_FAIL          = 'SUBMIT_FIN_PLAN_GOAL_FORM_FAIL';
export const UPDATE_FIN_PLAN_CURRENT_GOAL            = 'UPDATE_FIN_PLAN_CURRENT_GOAL';

// FinPlan Education Goals
export const SUBMIT_EDUCATION_GOALS_FORM             = 'SUBMIT_EDUCATION_GOALS_FORM';
export const SUBMIT_EDUCATION_GOALS_FORM_FAIL        = 'SUBMIT_EDUCATION_GOALS_FORM_FAIL';
export const SUBMIT_EDUCATION_GOALS_FORM_SUCCESS     = 'SUBMIT_EDUCATION_GOALS_FORM_SUCCESS';

// Personal Details Info
export const SUBMIT_PERSONAL_DETAILS_INFO_FORM           = 'SUBMIT_PERSONAL_DETAILS_INFO_FORM';
export const SHOW_PERSONAL_DETAILS_NO_TAX_FILED_ERROR    = 'SHOW_PERSONAL_DETAILS_NO_TAX_FILED_ERROR';
export const HIDE_PERSONAL_DETAILS_NO_TAX_FILED_ERROR    = 'HIDE_PERSONAL_DETAILS_NO_TAX_FILED_ERROR';
export const SUBMIT_PERSONAL_DETAILS_INFO_FORM_SUCCESS   = 'SUBMIT_PERSONAL_DETAILS_INFO_FORM_SUCCESS';

// FinPlan Purchase Goals
export const SUBMIT_PURCHASE_GOALS_FORM             = 'SUBMIT_PURCHASE_GOALS_FORM';
export const SUBMIT_PURCHASE_GOALS_FORM_FAIL        = 'SUBMIT_PURCHASE_GOALS_FORM_FAIL';
export const SUBMIT_PURCHASE_GOALS_FORM_SUCCESS     = 'SUBMIT_PURCHASE_GOALS_FORM_SUCCESS';

// FinPlan Retirement Goals
export const SUBMIT_RETIREMENT_GOALS_FORM           = 'SUBMIT_PURCHASE_GOALS_FORM';
export const SUBMIT_RETIREMENT_GOALS_FORM_FAIL      = 'SUBMIT_PURCHASE_GOALS_FORM_FAIL';
export const SUBMIT_RETIREMENT_GOALS_FORM_SUCCESS   = 'SUBMIT_PURCHASE_GOALS_FORM_SUCCESS';

// FinPlan Tax Return
export const UPDATE_FIN_PLAN_TAX_RETURN_SUCCESS     = 'UPDATE_FIN_PLAN_TAX_RETURN_SUCCESS';
export const TOGGLE_FIN_PLAN_TAX_RETURN_FORM        = 'TOGGLE_FIN_PLAN_TAX_RETURN_FORM';
export const UPDATE_FIN_PLAN_SUCCESS_FIRST_VISIT    = 'UPDATE_FIN_PLAN_SUCCESS_FIRST_VISIT';

// Goals
export const CHANGE_REPAYMENT_METHOD                = 'CHANGE_REPAYMENT_METHOD';
export const SET_GOALS_SELECTED_ACCOUNT_ID          = 'SET_GOALS_SELECTED_ACCOUNT_ID';
export const SUBMIT_GOAL_FORM_SUCCESS               = 'SUBMIT_GOAL_FORM_SUCCESS';
export const SUBMIT_GOAL_FORM_FAIL                  = 'SUBMIT_GOAL_FORM_FAIL';
export const UPDATE_GOAL_SUCCESS                    = 'UPDATE_GOAL_SUCCESS';
export const UPDATE_GOAL_FAIL                       = 'UPDATE_GOAL_FAIL';

// Settings
export const TOGGLE_ACCOUNT_SUCCESS                   = 'TOGGLE_ACCOUNT_SUCCESS';
export const TOGGLE_ACCOUNT_FAIL                      = 'TOGGLE_ACCOUNT_FAIL';
export const UPDATE_ACCOUNT_SUCCESS                   = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAIL                      = 'UPDATE_ACCOUNT_FAIL';
export const GET_STRIPE_INFO_SUCCESS                  = 'GET_STRIPE_INFO_SUCCESS';
export const GET_STRIPE_INFO_FAIL                     = 'GET_STRIPE_INFO_FAIL';
export const GET_EDITABLE_FIELDSETS_SUCCESS           = 'GET_EDITABLE_FIELDSETS_SUCCESS';
export const GET_EDITABLE_FIELDSETS_FAIL              = 'GET_EDITABLE_FIELDSETS_FAIL';
export const UPDATE_EDITABLE_FIELDSET_SUCCESS         = 'UPDATE_EDITABLE_FIELDSET_SUCCESS';
export const UPDATE_EDITABLE_FIELDSET_FAIL            = 'UPDATE_EDITABLE_FIELDSET_FAIL';
export const GET_STRIPE_SUBSCRIPTION_INFO_SUCCESS     = 'GET_STRIPE_SUBSCRIPTION_INFO_SUCCESS';
export const GET_STRIPE_SUBSCRIPTION_INFO_FAIL        = 'GET_STRIPE_SUBSCRIPTION_INFO_FAIL';
export const CANCEL_STRIPE_SUBSCRIPTION_SUCCESS       = 'CANCEL_STRIPE_SUBSCRIPTION_SUCCESS';
export const CANCEL_STRIPE_SUBSCRIPTION_FAIL          = 'CANCEL_STRIPE_SUBSCRIPTION_FAIL';
export const SET_USER_DATA_UPDATED_STATUS             = 'SET_USER_DATA_UPDATED_STATUS';
export const UPDATE_USER_DATA_SETTINGS_FAIL           = 'UPDATE_USER_DATA_SETTINGS_FAIL';
export const TOGGLE_SHOW_SETTINGS_CO_CLIENT_FIELDS    = 'TOGGLE_SHOW_SETTINGS_CO_CLIENT_FIELDS';
export const CHANGE_SETTINGS_NUMBER_OF_CHILDREN       = 'CHANGE_SETTINGS_NUMBER_OF_CHILDREN';
export const SET_PREFERENCES_SUBMISSION_ERROR         = 'SET_PREFERENCES_SUBMISSION_ERROR';
export const CHANGE_SETTNGS_FORM_FIELD_TYPE           = 'CHANGE_SETTNGS_FORM_FIELD_TYPE';
export const TOGGLE_SETTINGS_ADVISOR_CALL_INFORMATION = 'TOGGLE_SETTINGS_ADVISOR_CALL_INFORMATION';
export const SUBMIT_FIN_PLAN_INFO                      = 'SUBMIT_FIN_PLAN_INFO';

// Side NAV
// format
export const SIGNAL_ACCOUNTS_RENDERED               = 'SIGNAL_ACCOUNTS_RENDERED';
export const UPDATE_SIDE_NAV_DATA                   = 'UPDATE_SIDE_NAV_DATA';
export const GET_ENABLED_ACCOUNTS_SUCCESS           = 'GET_ENABLED_ACCOUNTS_SUCCESS';
export const GET_ENABLED_ACCOUNTS_FAIL              = 'GET_ENABLED_ACCOUNTS_FAIL';

// Bill Transactions Summary
export const CREATE_BILL_SUMMARY_SUCCESS             = 'CREATE_BILL_SUMMARY_SUCCESS ';
export const CREATE_BILL_SUMMARY_FAIL                = 'CREATE_BILL_SUMMARY_FAIL ';
export const BILLS_NOT_FOUND                         = 'BILLS_NOT_FOUND';
export const UPDATE_BILL                             = 'UPDATE_BILL';

// Income Transactions Summary
export const CREATE_INCOME_SUMMARY_SUCCESS          = 'CREATE_INCOME_SUMMARY_SUCCESS';
export const CREATE_INCOME_SUMMARY_FAIL             = 'CREATE_INCOME_SUMMARY_FAIL';
export const INCOMES_NOT_FOUND                      = 'INCOMES_NOT_FOUND';
export const UPDATE_INCOME                          = 'UPDATE_INCOME';
