export default {
  year: 'year',
  years: 'years',
  month: 'month',
  months: 'months',
  quarter: 'quarter',
  quarters: 'quarters',
  week: 'week',
  weeks: 'weeks',
  isoWeek: 'isoWeek',
  isoWeeks: 'isoWeeks',
  day: 'day',
  days: 'days',
  date: 'date',
  dates: 'dates',
  hour: 'hour',
  hours: 'hours',
  minute: 'minute',
  minutes: 'minutes',
  second: 'second',
  seconds: 'seconds'
};
