export default {
  alabama: 'ALABAMA',
  alaska: 'ALASKA',
  arizona: 'ARIZONA',
  arkansas: 'ARKANSAS',
  california: 'CALIFORNIA',
  colorado: 'COLORADO',
  connecticut: 'CONNECTICUT',
  delaware: 'DELAWARE',
  florida: 'FLORIDA',
  georgia: 'GEORGIA',
  hawaii: 'HAWAII',
  idaho: 'IDAHO',
  illinois: 'ILLINOIS',
  indiana: 'INDIANA',
  iowa: 'IOWA',
  kansas: 'KANSAS',
  kentucky: 'KENTUCKY',
  louisiana: 'LOUISIANA',
  maine: 'MAINE',
  maryland: 'MARYLAND',
  massachusetts: 'MASSACHUSETTS',
  michigan: 'MICHIGAN',
  minnesota: 'MINNESOTA',
  mississippi: 'MISSISSIPPI',
  missouri: 'MISSOURI',
  montana: 'MONTANA',
  nebraska: 'NEBRASKA',
  nevada: 'NEVADA',
  'new hampshire': 'NEW HAMPSHIRE',
  'new jersey': 'NEW JERSEY',
  'new mexico': 'NEW MEXICO',
  'new york': 'NEW YORK',
  'north carolina': 'NORTH CAROLINA',
  'north dakota': 'NORTH DAKOTA',
  ohio: 'OHIO',
  oklahoma: 'OKLAHOMA',
  oregon: 'OREGON',
  pennsylvania: 'PENNSYLVANIA',
  'rhode island': 'RHODE ISLAND',
  'south carolina': 'SOUTH CAROLINA',
  'south dakota': 'SOUTH DAKOTA',
  tennessee: 'TENNESSEE',
  texas: 'TEXAS',
  utah: 'UTAH',
  vermont: 'VERMONT',
  virginia: 'VIRGINIA',
  washington: 'WASHINGTON',
  'west virginia': 'WEST VIRGINIA',
  wisconsin: 'WISCONSIN',
  wyoming: 'WYOMING'
};
