export default {
  nickname: 'nickname',
  balanceAtGoalStart: 'balanceAtGoalStart',
  interestRate: 'interestRate',
  goalAmount: 'goalAmount',
  projectedRR: 'projectedRR',
  termInMonths: 'termInMonths',
  remainingPerExPerMonth: 'remainingPerExPerMonth',
  paymentPerMonth: 'paymentPerMonth',
  totalInterest: 'totalInterest',
  remainingTotalInterest: 'remainingTotalInterest',
  desiredTermInMonths: 'desiredTermInMonths',
  desiredTermInYears: 'desiredTermInYears',
  interestSaved: 'interestSaved',
  desiredPaymentPerMonth: 'desiredPaymentPerMonth',
  adjustedPaymentPerMonth: 'adjustedPaymentPerMonth',
  minimumPayment: 'minimumPayment',
  originalBalance: 'originalBalance',
  remainingTermInMonths: 'remainingTermInMonths',
  type: 'type',
  id: 'id',
  userId: 'userId',
  accountId: 'accountId'
};
