export default {
  firstName: 'firstName',
  lastName: 'lastName',
  birthdate: 'birthdate',
  age: 'age',
  gender: 'gender',
  firstNameCoClient: 'firstNameCoClient',
  lastNameCoClient: 'lastNameCoClient',
  birthdateCoClient: 'birthdateCoClient',
  genderCoClient: 'genderCoClient',
  email: 'email',
  currentPassword: 'currentPassword',
  newPassword: 'newPassword',
  confirmNewPassword: 'confirmNewPassword',
  phone: 'phone',
  hasSubmitedTaxReturnsInLastTwoYears: 'hasSubmitedTaxReturnsInLastTwoYears',
  maritalStatus: 'maritalStatus',
  numberOfChildren: 'numberOfChildren',
  permission: 'permission',
  zipCode: 'zipCode',
  state: 'state',
  income: 'income',
  debt: 'debt',
  objective: 'objective',
  experience: 'experience'
};
