export default {
  annuityForm: 'annuityForm',
  propertyForm: 'propertyForm',
  businessForm: 'businessForm',
  goalTypeForm: 'goalTypeForm',
  loanGoalForm: 'loanGoalForm',
  insuranceForm: 'insuranceForm',
  taxReturnForm: 'taxReturnForm',
  retirementForm: 'retirementForm',
  savingsGoalForm: 'savingsGoalForm',
  preferencesForm: 'preferencesForm',
  purchaseGoalsForm: 'purchaseGoalsForm',
  educationGoalsForm: 'educationGoalsForm',
  investmentGoalForm: 'investmentGoalForm',
  creditCardGoalForm: 'creditCardGoalForm',
  retirementGoalsForm: 'retirementGoalsForm',
  financialQuestionsForm: 'financialQuestionsForm',
  advisorConnectInfoForm: 'advisorConnectInfoForm',
  employerSelfEmploymentForm: 'employerSelfEmploymentForm',
  addAssetForm: 'addAssetForm',
};
