module.exports = {
  addTaxReturnInfo: 'addTaxReturnInfo',
  filingStatus: 'filingStatus',
  taxableInterest: 'taxableInterest',
  taxExemptInterest: 'taxExemptInterest',
  ordinaryDividends: 'ordinaryDividends',
  soleProprietorBusinessName: 'soleProprietorBusinessName',
  soleProprietorIncomeLoss: 'soleProprietorIncomeLoss',
  soleProprietorDepreciationAmortization: 'soleProprietorDepreciationAmortization',
  soleProprietorInterestExpense: 'soleProprietorInterestExpense',
  soleProprietorAssociatedLoan: 'soleProprietorAssociatedLoan',
  investmentRealEstatePropertyDescription: 'investmentRealEstatePropertyDescription',
  investmentRealEstateIncomeLoss: 'investmentRealEstateIncomeLoss',
  investmentRealEstateDepreciationAmortization: 'investmentRealEstateDepreciationAmortization',
  investmentRealEstateInterestExpense: 'investmentRealEstateInterestExpense',
  investmentRealEstateAssociatedLoan: 'investmentRealEstateAssociatedLoan',
  businessCashFlowBusinessName: 'businessCashFlowBusinessName',
  businessCashFlowIncomeLoss: 'businessCashFlowIncomeLoss',
  businessCashFlowDepreciationAmortization: 'businessCashFlowDepreciationAmortization',
  businessCashFlowInterestExpense: 'businessCashFlowInterestExpense',
  businessCashFlowContributions: 'businessCashFlowContributions',
  businessCashFlowDistributions: 'businessCashFlowDistributions',
  businessCashFlowAssociatedLoan: 'businessCashFlowAssociatedLoan'
};
